// 请求和 headers 之间不能有空行
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "User id of the note creator is at the start sent along the request",
  "important": true,
  "userId": "67700f88861825cbbb38dd64"
}

# {
#   "content": "A object only has 'content' property"
# }

// 多个请求用 ### 分隔
###
GET http://localhost:3001/api/notes
###
DELETE http://localhost:3001/api/notes/6762d56042193d0bc1dfe557
