// 请求和 headers 之间不能有空行
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Ensure that everything still works",
  "important": true
}

# {
#   "content": "A object only has 'content' property"
# }

// 多个请求用 ### 分隔
###
GET http://localhost:3001/api/notes
###
DELETE http://localhost:3001/api/notes/6762d56042193d0bc1dfe557
