// 请求和 headers 之间不能有空行
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFteWxvdmVzb25nIiwiaWQiOiI2NzcwMGY4ODg2MTgyNWNiYmIzOGRkNjQiLCJpYXQiOjE3MzU5ODgyOTB9.dcpdYasCPl9t5wLVy6TgvD6NCXAbrLx8vZHvara6pcw

{
  "content": "Single page apps use token based auth",
  "important": false
}

# {
#   "content": "A object only has 'content' property"
# }

// 多个请求用 ### 分隔
###
GET http://localhost:3001/api/notes
###
DELETE http://localhost:3001/api/notes/6762d56042193d0bc1dfe557
